services:
  postgres:
    build: .
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: perd
      POSTGRES_USER: perd
      POSTGRES_DB: perd
    command: postgres -c max_connections=1000
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
