services:
  postgres-perd:
    image: postgres:18
    container_name: postgres-perd
    environment:
      POSTGRES_PASSWORD: perd
      POSTGRES_USER: perd
      POSTGRES_DB: perd
    command: -c max_connections=1000
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_perd:/var/lib/postgresql
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U perd' ]
      interval: 10s
      timeout: 5s
      retries: 5

  # https://neon.com/guides/local-development-with-neon
  # https://github.com/neondatabase/neon/issues/4989
  # https://github.com/neondatabase/serverless/issues/33#issuecomment-1634853042
  # https://github.com/TimoWilhelm/local-neon-http-proxy/tree/main
  # https://readme.localtest.me/
  neon-proxy:
    container_name: neon-proxy-perd
    image: ghcr.io/perdolique/local-neon-proxy:main
    environment:
      - PG_CONNECTION_STRING=postgres://perd:perd@postgres-perd:5432/perd
    restart: unless-stopped
    ports:
      - '4444:4444'
    depends_on:
      postgres-perd:
        condition: service_healthy

volumes:
  postgres_perd:
