allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: false
  workerd: false
minimumReleaseAgeExclude:
  - worsier-darwin-arm64@2.9.0
  - worsier-darwin-x64@2.9.0
  - worsier-linux-arm64-gnu@2.9.0
  - worsier-linux-arm64-musl@2.9.0
  - worsier-linux-x64-gnu@2.9.0
  - worsier-linux-x64-musl@2.9.0
  - worsier-win32-arm64-msvc@2.9.0
  - worsier-win32-x64-msvc@2.9.0
  - worsier@2.9.0
publicHoistPattern:
  - h3
