allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: false
  workerd: false
minimumReleaseAgeExclude:
  - '@clack/core@1.5.1'
  - '@clack/prompts@1.8.1'
  - '@iconify/collections@1.0.736'
  - '@nuxt/icon@2.5.1'
  - '@nuxt/devtools@3.4.2'
  - '@nuxt/scripts@1.3.9'
  - '@playwright/test@1.63.0'
  - '@tybys/wasm-util@0.10.4'
  - '@types/node@26.6.2'
  - ansis@4.4.0
  - eslint-config-greenpie@17.12.0
  - oxlint@1.85.0
  - oxlint-tsgolint@7.0.2003
  - tsx@4.23.15
  - valibot@1.5.0
  - vite@8.3.1
  - vue-router@5.3.1
  - vue-tsc@3.3.11
  - worsier-darwin-arm64@3.6.0
  - worsier-darwin-x64@3.6.0
  - worsier-linux-arm64-gnu@3.6.0
  - worsier-linux-arm64-musl@3.6.0
  - worsier-linux-x64-gnu@3.6.0
  - worsier-linux-x64-musl@3.6.0
  - worsier-win32-arm64-msvc@3.6.0
  - worsier-win32-x64-msvc@3.6.0
  - worsier@3.6.0
  - wrangler@4.139.0
  - '@nuxt/devtools-kit@3.4.2'
  - '@nuxt/devtools-wizard@3.4.2'
  - '@cloudflare/workerd-darwin-64@1.20260911.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260911.1'
  - '@cloudflare/workerd-linux-64@1.20260911.1'
  - '@cloudflare/workerd-linux-arm64@1.20260911.1'
  - '@cloudflare/workerd-windows-64@1.20260911.1'
  - miniflare@5.20260911.0-alpha || 5.20260923.0-alpha
  - workerd@1.20260911.1
  - '@oxlint-tsgolint/darwin-arm64@7.0.2003'
  - '@oxlint-tsgolint/darwin-x64@7.0.2003'
  - '@oxlint-tsgolint/linux-arm64@7.0.2003'
  - '@oxlint-tsgolint/linux-x64@7.0.2003'
  - '@oxlint-tsgolint/win32-arm64@7.0.2003'
  - '@oxlint-tsgolint/win32-x64@7.0.2003'
publicHoistPattern:
  - h3
