allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: false
  workerd: false
minimumReleaseAgeExclude:
  - '@iconify-json/hugeicons@1.2.31'
  - markdownlint-cli@0.49.1
  - pinia@4.0.2
publicHoistPattern:
  - h3
