name: Database migration (staging)

permissions:
  contents: read

on:
  pull_request:
    branches:
      - master
    paths:
      - 'server/database/migrations/**'
      - .github/workflows/database-migration-staging.yml

jobs:
  migration:
    runs-on: ubuntu-24.04
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run database migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm run db:migrate
      - name: Seed database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm run db:seed
